/*
 *  Copyright 2016-2023 Qameta Software OÜ
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package org.allurereport.jenkins.callables;

import hudson.FilePath;
import hudson.remoting.VirtualChannel;
import jenkins.MasterToSlaveFileCallable;

import java.io.File;
import java.io.IOException;
import java.io.Writer;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Properties;

public class AddEnvironmentInfo extends MasterToSlaveFileCallable<FilePath> {

    public static final String ENV_PROPERTIES = "environment.properties";

    private final String name;
    private final long start;
    private final long stop;

    public AddEnvironmentInfo(final String name, final long start, final long stop) {
        this.name = name;
        this.start = start;
        this.stop = stop;
    }

    @Override
    public FilePath invoke(final File file, final VirtualChannel channel) throws IOException {
        final Path outputDirectory = Paths.get(file.toURI()).toRealPath();
        Files.createDirectories(outputDirectory);
        final Path envFile = outputDirectory.resolve(ENV_PROPERTIES);

        final Properties props = new Properties();
        props.setProperty("jenkins.run.name", name);
        props.setProperty("jenkins.run.start", Long.toString(start));
        props.setProperty("jenkins.run.stop", Long.toString(stop));

        try (Writer writer = Files.newBufferedWriter(envFile, StandardCharsets.UTF_8)) {
            props.store(writer, "Generated by Allure Jenkins Plugin");

            return new FilePath(envFile.toFile());
        }
    }
}
