name: Release
run-name: Release ${{ inputs.releaseVersion }} (next ${{ inputs.nextVersion }}) by ${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: "The release version to publish (for example 2.36.0)"
        required: true
      nextVersion:
        description: "The next development version without the -SNAPSHOT suffix"
        required: true

permissions:
  contents: read

jobs:
  triage:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: "Check release version"
        run: |
          echo "${{ github.event.inputs.releaseVersion }}" | grep -Eq '^[0-9]+(\.[0-9]+)+$'
      - name: "Check next version"
        run: |
          echo "${{ github.event.inputs.nextVersion }}" | grep -Eq '^[0-9]+(\.[0-9]+)+$'
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.ref_name }}
          fetch-depth: 0
          token: ${{ secrets.QAMETA_CI }}
      - name: "Configure CI Git User"
        run: |
          git config --global user.name qameta-ci
          git config --global user.email qameta-ci@qameta.io
      - name: "Set release version"
        run: |
          sed -i -E 's#<revision>.*</revision>#<revision>${{ github.event.inputs.releaseVersion }}</revision>#' pom.xml
          sed -i -E 's#<changelist>.*</changelist>#<changelist></changelist>#' pom.xml
          grep -E '<revision>|<changelist>' pom.xml
      - name: "Commit release version and create tag"
        run: |
          git commit -am "release ${{ github.event.inputs.releaseVersion }}"
          git tag ${{ github.event.inputs.releaseVersion }}
          git push origin ${{ github.event.inputs.releaseVersion }}
      - name: "Set next development version"
        run: |
          sed -i -E 's#<revision>.*</revision>#<revision>${{ github.event.inputs.nextVersion }}</revision>#' pom.xml
          sed -i -E 's#<changelist>.*</changelist>#<changelist>-SNAPSHOT</changelist>#' pom.xml
          grep -E '<revision>|<changelist>' pom.xml
      - name: "Commit next development version and push it"
        run: |
          git commit -am "set next development version ${{ github.event.inputs.nextVersion }}"
          git push origin ${{ github.ref_name }}
      - name: "Publish GitHub Release"
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/${{ github.repository }}/releases
          tag_name: ${{ github.event.inputs.releaseVersion }}
          generate_release_notes: true
          target_commitish: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.QAMETA_CI }}
