#name: Release
#
#on:
#  release:
#    types: [published]
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v1
#    - name: Set up JDK
#      uses: actions/setup-java@v1
#      with:
#        java-version: 1.8
#    - name: "Gradle Build"
#      run: ./gradlew build -Pversion=${GITHUB_REF:10}
#    - name: "Gradle Publish to Artofactory"
#      env:
#        ARTIFACTORY_USER: ${{ secrets.ARTIFACTORY_USER }}
#        ARTIFACTORY_PASS: ${{ secrets.ARTIFACTORY_PASS }}
#      run: ./gradlew artifactoryPublish -Pversion=${GITHUB_REF:10}
