name: Release

on:
  release:
    types: [ published ]

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
          server-id: maven.jenkins-ci.org
          server-username: ${{ secrets.JENKINS_USERNAME }}
          server-password: ${{ secrets.JENKINS_TOKEN }}
      - run: |
          ./mvnw versions:set -DnewVersion=${GITHUB_REF:10}
          ./mvnw deploy
